# mybatis 配置
mybatis:
  type-aliases-package: cn.laochou.seckill.pojo
  configuration:
    map-underscore-to-camel-case: true
    # 一个提升性能的配置
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:mappers/*.xml


spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: laochou
    type: com.alibaba.druid.pool.DruidDataSource
  # redis 配置
  redis:
    host: 192.168.81.120
    port: 6379
    password: laochou
    timeout: 1000
  # rabbitmq 配置
  rabbitmq:
    host: 192.168.81.120
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        # 代表消费者的数量
        concurrency: 10
        max-concurrency: 10
        # 表示从队列中，每次取几个
        prefetch: 1
        # 消费者自动启动
        auto-startup: true
        # 消费失败，会进行重试
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1